//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Persona> PersonaSet { get; set; }
        public virtual DbSet<Personal> PersonalSet { get; set; }
        public virtual DbSet<Cargo> CargoSet { get; set; }
        public virtual DbSet<Tipo_Contrato> Tipo_ContratoSet { get; set; }
        public virtual DbSet<Nivel> NivelSet { get; set; }
        public virtual DbSet<Usuario> UsuarioSet { get; set; }
        public virtual DbSet<Conyugue> ConyugueSet { get; set; }
        public virtual DbSet<Hijo> HijoSet { get; set; }
        public virtual DbSet<Reporte_edicion> Reporte_edicionSet { get; set; }
        public virtual DbSet<Estado> EstadoSet { get; set; }
    }
}
