//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public int Id { get; set; }
        public string HaberBasico { get; set; }
        public string FechaIngreso { get; set; }
        public string FechaRegistro { get; set; }
        public string DireccionRegional { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Cargo Cargo1 { get; set; }
        public virtual Tipo_Contrato Tipo_Contrato { get; set; }
        public virtual Nivel Nivel1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
