//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte_edicion
    {
        public int Id { get; set; }
        public string Fecha_Edicion { get; set; }
        public string Persona_Editada { get; set; }
        public string Tipo_edicion { get; set; }
        public string Usario_Editor { get; set; }
    }
}
